### PR TITLE
add allowlist to securityConfig

### PR DESCRIPTION
**Pull request by semisimple**
Hello colleagues,

my team would like to use the auto-configuration but needs to keep some of our old (unprotected) endpoints available as we migrate step by step.

This makes it possible to configure multiple allowed endpoints (instead of just the actuators). It keeps the old behaviour (/actuator/**) as a fallback.

Thank you for your work again, kindest regards and talk to you soon :),

Robert

### CODE REVIEW

**Comment by j0xaf** [comment]
Hi @semisimple,  thank you for your contribution. To make sure that the added functionality does not break existing users: could you please add a test showing that the default functionality of `io.dwpbank.movewp3.microservice.security.whitelist` is working (ie `/actuator` is accessible)? Thank you!

**Comment by semisimple** [comment]
> Hi @semisimple, thank you for your contribution. To make sure that the added functionality does not break existing users: could you please add a test showing that the default functionality of `io.dwpbank.movewp3.microservice.security.whitelist` is working (ie `/actuator` is accessible)? Thank you!

Hi, thanks for the feedback.I implemented the missing test by splitting it into two separate tests. One checks the default behaviour and one tests the new whitelist feature. :)

**Comment by semisimple** [comment]
Hi,

we tried the changes with a local build but ran into troubles when using Post-request (403 Forbidden).
Currently we are torn between different solutions:

- An ignoreList:
```
@Override
public void configure(WebSecurity web) throws Exception {
  web
    .ignoring()
    .antMatchers(whitelist);
}
@Override
protected void configure(HttpSecurity http) throws Exception {
...//as in master
```

- Ignoring csrf for the whitelist:
```
@Override
protected void configure(HttpSecurity http) throws Exception {
// @formatter:off
http
    .authorizeRequests()
        .antMatchers(whitelist)
            .permitAll()
        .anyRequest()
    .authenticated()
        .and()
    .oauth2ResourceServer().jwt();
// @formatter:on

http.sessionManagement()
   .sessionCreationPolicy(SessionCreationPolicy.STATELESS);

http.csrf()
   .ignoringAntMatchers(whitelist);
} 
```

**Comment by ginkel** [comment]
Hi @semisimple,

in order to merge your PR, I'd like it to have it build successfully. Could you please rebase your branch against the `main` branch? This should solve the `openssl` problem`

Thanks,
Thilo

**Comment by ginkel** [comment]
@semisimple I have created a new PR #8 based on the squashed changes from this PR. Thanks for your contribution!

**Pull request closed without merging**
